name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.2.1
  - seaborn=0.11.2
  - pandas=1.4.0
  - pip=21.3.1
  - pandas-profiling=3.1.0
  - pyarrow=6.0.1
  - pip:
      - wandb==0.12.9
