name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.2.1
  - seaborn=0.11.2
  - pandas=1.4.0
  - pip=21.3.1
  - pandas-profiling=3.0.0 # Version 3.1.0 is broken
  - pyarrow=6.0.1
  - wandb=0.12.9
  - ipywidgets=7.6.5