name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.23.1
  - pyyaml=6.0
  - hydra-core=1.1.1
  - requests=2.27.1
  - pandas=1.4.0
  - scikit-learn=1.0.2
  - pytest=6.2.5
  - scipy=1.7.3
  - matplotlib=3.5.1
  - pillow=8.4.0
  - jupyterlab=3.2.1
  - seaborn=0.11.2
  - pandas-profiling=3.1.0
  - pyarrow=6.0.1
  - pip=21.3.1
  - wandb==0.12.9