name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.0
  - pip=21.3.1
  - mlflow=1.23.1
  - scikit-learn=1.0.2
  - wandb==0.12.9
  - pip:
      - git+https://github.com/digitalemerge/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
