name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.0
  - pip=20.3.3
  - mlflow=1.23.1
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - pillow=8.4.0
  - wandb==0.12.9