name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.3.1
  - requests=2.27.1
  - mlflow=1.23.1
  - wandb==0.12.9
  - pip:
      - git+https://github.com/digitalemerge/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
